import "@/styles/common.scss";
import Header from "./components/organisms/header";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="ko">
			<body>
				<div id="wrap">
					<Header />
					{children}
				</div>
			</body>
		</html>
	);
}
